INSERT INTO ref.data_source (source_id, code, name, url, license) VALUES
  (1, 'cgmacros', 'CGMacros: a scientific dataset for personalized nutrition and diet monitoring',
   'https://physionet.org/content/cgmacros/1.0.0/', 'Open Data Commons Attribution License v1.0');

INSERT INTO ref.tag (tag_id, code, display, description) VALUES
  (1, 'composite-patient', 'Composite patient: real CGM/wearable data + synthetic EHR history',
      'Sensor data and baseline labs from a real CGMacros participant; EHR history generated by Synthea'),
  (2, 'gmi-inconsistent', 'HbA1c and CGM-derived GMI differ by more than 1.0 percentage point',
      'Recomputed by the pipeline from report.consistency'),
  (3, 'gmi-warn', 'HbA1c and CGM-derived GMI differ by 0.5-1.0 percentage point',
      'Recomputed by the pipeline from report.consistency'),
  (4, 'demo-featured', 'Featured in demo', 'Assigned manually'),
  (5, 'needs-review', 'Needs clinical review', 'Assigned manually');

-- Codes stored in core.lab_result (measured values) ...
INSERT INTO ref.observation_code (code_id, loinc, display, ucum_unit) VALUES
  (1,  '4548-4',   'Hemoglobin A1c/Hemoglobin.total in Blood',                      '%'),
  (2,  '1558-6',   'Fasting glucose [Mass/volume] in Serum or Plasma',              'mg/dL'),
  (3,  '20448-7',  'Insulin [Units/volume] in Serum or Plasma',                     'u[IU]/mL'),
  (4,  '2093-3',   'Cholesterol [Mass/volume] in Serum or Plasma',                  'mg/dL'),
  (5,  '2085-9',   'Cholesterol in HDL [Mass/volume] in Serum or Plasma',           'mg/dL'),
  (6,  '2571-8',   'Triglyceride [Mass/volume] in Serum or Plasma',                 'mg/dL'),
  (7,  '29463-7',  'Body weight',                                                   'kg'),
  (8,  '8302-2',   'Body height',                                                   'cm'),
-- ... and codes only emitted to FHIR, computed from views.
  (20, '39156-5',  'Body mass index (BMI) [Ratio]',                                 'kg/m2'),
  (21, '13457-7',  'Cholesterol in LDL [Mass/volume] in Serum or Plasma by calculation', 'mg/dL'),
  (22, '97507-8',  'Average glucose [Mass/volume] in Interstitial fluid during Reporting Period', 'mg/dL'),
  (23, '97506-0',  'Glucose management indicator',                                  '%'),
  (24, '106793-3', 'Glucose times in ranges panel',                                 '%'),
  (25, '104642-4', 'Time in very low range (<54 mg/dL)',                            '%'),
  (26, '104641-6', 'Time in low range (54-69 mg/dL)',                               '%'),
  (27, '97510-2',  'Time in target range (70-180 mg/dL)',                           '%'),
  (28, '104640-8', 'Time in high range (181-250 mg/dL)',                            '%'),
  (29, '104639-0', 'Time in very high range (>250 mg/dL)',                          '%'),
  (30, '104638-2', 'Glucose coefficient of variation',                              '%'),
  (31, '8867-4',   'Heart rate',                                                    '/min'),
  (32, '99504-3',  'Glucose [Mass/volume] in Interstitial fluid',                   'mg/dL'),
  (33, '41653-7',  'Glucose [Mass/volume] in Capillary blood by Glucometer',        'mg/dL');

INSERT INTO ref.device_model (model_id, manufacturer, model_name, kind, specimen, nominal_interval) VALUES
  (1, 'Dexcom',         'G6 Pro',              'cgm',        'interstitial', INTERVAL '5 minutes'),
  (2, 'Abbott',         'FreeStyle Libre Pro', 'cgm',        'interstitial', INTERVAL '15 minutes'),
  (3, 'Ascensia',       'Contour Next',        'glucometer', 'capillary',    NULL),
  (4, 'Fitbit',         'Sense',               'wearable',   NULL,           INTERVAL '1 minute');
