"""`init-db`: create the twin schema on the TimescaleDB instance. Idempotent.

1. timescaledb extension and the ref/core/ts/report schemas
2. tables, enums and constraints from the ORM models (create_all)
3. hypertables + compression on the ts.* reading tables
4. continuous aggregates (twin/sql/continuous_aggregates.sql)
5. report views, recreated each time (twin/sql/report_views.sql)
6. reference data, upserted
"""

from __future__ import annotations

from datetime import timedelta
from importlib.resources import files

from sqlalchemy import text
from sqlalchemy.dialects.postgresql import insert

from twin.db import engine, session_scope
from twin.models import Base, DataSource, DeviceKind, DeviceModel, FitbitReading, GlucoseReading, ObservationCode, Tag

SCHEMAS = ("ref", "core", "ts", "report")
HYPERTABLES = (GlucoseReading, FitbitReading)

DATA_SOURCES = [
    {"source_id": 1, "code": "cgmacros",
     "name": "CGMacros: a scientific dataset for personalized nutrition and diet monitoring",
     "url": "https://physionet.org/content/cgmacros/1.0.0/", "license": "Open Data Commons Attribution License v1.0"},
]

TAGS = [
    {"tag_id": 1, "code": "composite-patient", "display": "Composite patient: real CGM/wearable data + synthetic EHR history",
     "description": "Sensor data and baseline labs from a real CGMacros participant; EHR history generated by Synthea"},
    {"tag_id": 2, "code": "gmi-inconsistent", "display": "HbA1c and CGM-derived GMI differ by more than 1.0 percentage point",
     "description": "Recomputed by the pipeline from report.consistency"},
    {"tag_id": 3, "code": "gmi-warn", "display": "HbA1c and CGM-derived GMI differ by 0.5-1.0 percentage point",
     "description": "Recomputed by the pipeline from report.consistency"},
    {"tag_id": 4, "code": "demo-featured", "display": "Featured in demo", "description": "Assigned manually"},
    {"tag_id": 5, "code": "needs-review", "display": "Needs clinical review", "description": "Assigned manually"},
]

# 1-8 are stored in core.lab_result (measured); the rest are only emitted to FHIR.
OBSERVATION_CODES = [
    (1, "4548-4", "Hemoglobin A1c/Hemoglobin.total in Blood", "%"),
    (2, "1558-6", "Fasting glucose [Mass/volume] in Serum or Plasma", "mg/dL"),
    (3, "20448-7", "Insulin [Units/volume] in Serum or Plasma", "u[IU]/mL"),
    (4, "2093-3", "Cholesterol [Mass/volume] in Serum or Plasma", "mg/dL"),
    (5, "2085-9", "Cholesterol in HDL [Mass/volume] in Serum or Plasma", "mg/dL"),
    (6, "2571-8", "Triglyceride [Mass/volume] in Serum or Plasma", "mg/dL"),
    (7, "29463-7", "Body weight", "kg"),
    (8, "8302-2", "Body height", "cm"),
    (20, "39156-5", "Body mass index (BMI) [Ratio]", "kg/m2"),
    (21, "13457-7", "Cholesterol in LDL [Mass/volume] in Serum or Plasma by calculation", "mg/dL"),
    (22, "97507-8", "Average glucose [Mass/volume] in Interstitial fluid during Reporting Period", "mg/dL"),
    (23, "97506-0", "Glucose management indicator", "%"),
    (24, "106793-3", "Glucose times in ranges panel", "%"),
    (25, "104642-4", "Time in very low range (<54 mg/dL)", "%"),
    (26, "104641-6", "Time in low range (54-69 mg/dL)", "%"),
    (27, "97510-2", "Time in target range (70-180 mg/dL)", "%"),
    (28, "104640-8", "Time in high range (181-250 mg/dL)", "%"),
    (29, "104639-0", "Time in very high range (>250 mg/dL)", "%"),
    (30, "104638-2", "Glucose coefficient of variation", "%"),
    (31, "8867-4", "Heart rate", "/min"),
    (32, "99504-3", "Glucose [Mass/volume] in Interstitial fluid", "mg/dL"),
    (33, "41653-7", "Glucose [Mass/volume] in Capillary blood by Glucometer", "mg/dL"),
]

DEVICE_MODELS = [
    (1, "Dexcom", "G6 Pro", DeviceKind.cgm, "interstitial", timedelta(minutes=5)),
    (2, "Abbott", "FreeStyle Libre Pro", DeviceKind.cgm, "interstitial", timedelta(minutes=15)),
    (3, "Ascensia", "Contour Next", DeviceKind.glucometer, "capillary", None),
    (4, "Fitbit", "Sense", DeviceKind.wearable, None, timedelta(minutes=1)),
]


def _statements(resource: str) -> list[str]:
    sql = files("twin").joinpath("sql", resource).read_text()
    return [s.strip() for s in sql.split(";\n") if s.strip() and not all(
        line.strip().startswith("--") or not line.strip() for line in s.splitlines())]


async def _upsert(session, model, rows: list[dict]) -> None:
    stmt = insert(model).values(rows)
    pk = [c.name for c in model.__table__.primary_key]
    await session.execute(
        stmt.on_conflict_do_update(index_elements=pk, set_={c: stmt.excluded[c] for c in rows[0] if c not in pk})
    )


async def init_db(log=print) -> None:
    # DDL that TimescaleDB requires outside a transaction block -> autocommit.
    async with engine().connect() as conn:
        conn = await conn.execution_options(isolation_level="AUTOCOMMIT")
        await conn.exec_driver_sql("CREATE EXTENSION IF NOT EXISTS timescaledb")
        for schema in SCHEMAS:
            await conn.exec_driver_sql(f"CREATE SCHEMA IF NOT EXISTS {schema}")
        await conn.run_sync(Base.metadata.create_all)
        log(f"tables: {len(Base.metadata.tables)}")

        for model in HYPERTABLES:
            name = f"{model.__table__.schema}.{model.__table__.name}"
            await conn.execute(
                text("SELECT create_hypertable(:t, by_range('time', INTERVAL '7 days'), if_not_exists => TRUE)"),
                {"t": name},
            )
            compressed = await conn.scalar(
                text("SELECT compression_enabled FROM timescaledb_information.hypertables "
                     "WHERE hypertable_schema = :s AND hypertable_name = :n"),
                {"s": model.__table__.schema, "n": model.__table__.name},
            )
            if not compressed:
                await conn.exec_driver_sql(
                    f"ALTER TABLE {name} SET (timescaledb.compress, timescaledb.compress_segmentby = 'device_id')"
                )
        log(f"hypertables: {', '.join(m.__tablename__ for m in HYPERTABLES)}")

        for stmt in _statements("continuous_aggregates.sql"):
            await conn.exec_driver_sql(stmt)
        await conn.exec_driver_sql("DROP SCHEMA report CASCADE")
        await conn.exec_driver_sql("CREATE SCHEMA report")
        views = _statements("report_views.sql")
        for stmt in views:
            await conn.exec_driver_sql(stmt)
        log(f"continuous aggregates: 2, report views: {len(views)}")

    async with session_scope() as s:
        await _upsert(s, DataSource, DATA_SOURCES)
        await _upsert(s, Tag, TAGS)
        await _upsert(s, ObservationCode,
                      [dict(zip(("code_id", "loinc", "display", "ucum_unit"), r)) for r in OBSERVATION_CODES])
        await _upsert(s, DeviceModel, [
            dict(zip(("model_id", "manufacturer", "model_name", "kind", "specimen", "nominal_interval"), r))
            for r in DEVICE_MODELS
        ])
    log("reference data seeded")
