"""`summarize` step: Device resources and CGM / heart-rate / step summaries into FHIR.

Codes follow the HL7 CGM IG (https://build.fhir.org/ig/HL7/cgm/):
  97507-8 mean glucose, 106793-3 times-in-ranges panel, 104638-2 CV, 97506-0 GMI.
CGM values come from the fused stream (ts.glucose_fused), so those Observations carry
a `method` naming both CGMs instead of a single `device`. GMI is reported once over
the whole sensor window (it is defined over a multi-day period, not per day). Days
below 70 % coverage are skipped.
"""

from __future__ import annotations

from datetime import timedelta
from decimal import Decimal

from sqlalchemy import select

from twin.config import Settings
from twin.db import session_scope
from twin.fhir.client import FhirClient, twin_id
from twin.models import Device, DeviceKind, DeviceModel
from twin.models import views as v
from twin.pipeline.ehr import fhir_patients

TAG = {"system": "urn:healthcare-digital-twin:tags", "code": "composite-patient",
       "display": "Composite patient: real CGM/wearable data + synthetic EHR history"}
SYNTHETIC_TAG = {"system": "urn:healthcare-digital-twin:tags", "code": "synthetic-sensors",
                 "display": "Generated by the twin's rule-based wearable generator (synthetic)"}
MIN_COVERAGE_PCT = 70
LOINC = "http://loinc.org"
UCUM = "http://unitsofmeasure.org"
TIR_COMPONENTS = [
    ("pct_very_low", "104642-4", "Time in very low range (<54 mg/dL)"),
    ("pct_low", "104641-6", "Time in low range (54-69 mg/dL)"),
    ("pct_target", "97510-2", "Time in target range (70-180 mg/dL)"),
    ("pct_high", "104640-8", "Time in high range (181-250 mg/dL)"),
    ("pct_very_high", "104639-0", "Time in very high range (>250 mg/dL)"),
]
DEVICE_TYPE = {"cgm": "Continuous glucose monitor", "glucometer": "Blood glucose meter", "wearable": "Activity tracker"}


def _f(value) -> float:
    return float(value) if isinstance(value, Decimal) else value


def _qty(value, unit: str) -> dict:
    return {"value": _f(value), "unit": unit, "system": UCUM, "code": unit}


def _code(code: str, display: str) -> dict:
    return {"coding": [{"system": LOINC, "code": code, "display": display}], "text": display}


def _obs(oid, patient_id, device_id, code, display, start, end, category="laboratory", method=None, **value) -> dict:
    """device_id for single-device values; method (text) for values fused from several devices."""
    obs = {
        "resourceType": "Observation",
        "id": oid,
        "meta": {"tag": [TAG]},
        "status": "final",
        "category": [{"coding": [{"system": "http://terminology.hl7.org/CodeSystem/observation-category",
                                  "code": category}]}],
        "code": _code(code, display),
        "subject": {"reference": f"Patient/{patient_id}"},
        "effectivePeriod": {"start": start.isoformat(), "end": end.isoformat()},
        **value,
    }
    if device_id is not None:
        obs["device"] = {"reference": f"Device/{twin_id('device', device_id)}"}
    if method is not None:
        obs["method"] = {"text": method}
    return obs


async def run_summarize(cfg: Settings, log=print) -> dict[str, int]:
    counts = {"devices": 0, "observations": 0}
    async with FhirClient() as fhir:
        await fhir.wait_ready()
        async with session_scope() as s:
            patient_ids = list(await s.scalars(fhir_patients()))
        for patient_id in patient_ids:
            async with session_scope() as s:
                resources = await _patient_resources(s, patient_id, cfg)
            await fhir.put_all(resources)
            n_obs = sum(r["resourceType"] == "Observation" for r in resources)
            n_dev = sum(r["resourceType"] == "Device" for r in resources)
            counts["observations"] += n_obs
            counts["devices"] += n_dev
            log(f"{patient_id}: {n_obs} observations, {n_dev} devices")
    return counts


async def _patient_resources(s, patient_id, cfg: Settings) -> list[dict]:
    pid = str(patient_id)
    tz = cfg.tz
    resources = []
    devices = await s.scalars(select(Device).where(Device.patient_id == patient_id).order_by(Device.device_id))
    for device in devices:
        m = device.model
        resources.append({
            "resourceType": "Device",
            "id": twin_id("device", device.device_id),
            "meta": {"tag": [TAG]},
            "identifier": [{"system": "urn:healthcare-digital-twin:device", "value": str(device.device_id)}],
            "status": "active",
            "manufacturer": m.manufacturer,
            "deviceName": [{"name": f"{m.manufacturer} {m.model_name}", "type": "manufacturer-name"}],
            "type": {"text": DEVICE_TYPE[m.kind]},
            "patient": {"reference": f"Patient/{pid}"},
        })

    # CGM metrics come from the fused stream (both CGMs), so they carry a method, not a device.
    w = v.cgm_window.c
    window = (await s.execute(
        select(w.glucose_source, w.method_version, w.period_start, w.period_end, w.gmi).where(w.patient_id == patient_id)
    )).first()
    if window:
        source, version, start, end, gmi = window
        method = f"Fused CGM: {source} ({version})"
        resources.append(_obs(twin_id(pid, "cgm-gmi"), pid, None, "97506-0", "Glucose management indicator",
                              start.astimezone(tz), end.astimezone(tz), method=method, valueQuantity=_qty(gmi, "%")))

        c = v.cgm_daily.c
        daily = await s.execute(
            select(c.day, c.mean_mg_dl, c.cv_pct, c.pct_very_low, c.pct_low, c.pct_target, c.pct_high, c.pct_very_high)
            .where(c.patient_id == patient_id, c.coverage_pct >= MIN_COVERAGE_PCT)
            .order_by(c.day)
        )
        for day, mean, cv, *pcts in daily:
            day = day.astimezone(tz)
            end = day + timedelta(days=1)  # wall-clock day, correct across DST changes
            key = day.date().isoformat()
            resources.append(_obs(twin_id(pid, "cgm-mean", key), pid, None, "97507-8",
                                  "Average glucose in interstitial fluid", day, end, method=method,
                                  valueQuantity=_qty(mean, "mg/dL")))
            resources.append(_obs(twin_id(pid, "cgm-cv", key), pid, None, "104638-2",
                                  "Glucose coefficient of variation", day, end, method=method,
                                  valueQuantity=_qty(cv, "%")))
            resources.append(_obs(
                twin_id(pid, "cgm-tir", key), pid, None, "106793-3", "Glucose times in ranges", day, end,
                method=method,
                component=[{"code": _code(code, display), "valueQuantity": _qty(pct, "%")}
                           for (_, code, display), pct in zip(TIR_COMPONENTS, pcts)],
            ))

    # Wearable summaries (heart rate, steps) reference the patient's wearable device.
    wearables = dict((await s.execute(
        select(DeviceModel.is_synthetic, Device.device_id).join(DeviceModel, DeviceModel.model_id == Device.model_id)
        .where(Device.patient_id == patient_id, DeviceModel.kind == DeviceKind.wearable)
        .order_by(Device.device_id))).all())
    wearable_id, generator_id = wearables.get(False), wearables.get(True)
    a = v.activity_daily.c
    days = await s.execute(
        select(a.day, a.hr_mean, a.hr_minutes, a.steps).where(a.patient_id == patient_id).order_by(a.day)
    )
    for day, hr_mean, hr_minutes, steps in days:
        day = day.astimezone(tz)
        key = day.date().isoformat()
        if hr_mean is not None and (hr_minutes or 0) >= 1440 * MIN_COVERAGE_PCT / 100:
            resources.append(_obs(twin_id(pid, "hr-mean", key), pid, wearable_id, "8867-4",
                                  "Heart rate (daily mean)", day, day + timedelta(days=1),
                                  category="vital-signs", valueQuantity=_qty(round(hr_mean), "/min")))
        if steps is not None:
            resources.append(_obs(twin_id(pid, "steps", key), pid, wearable_id, "55423-8",
                                  "Number of steps (daily total)", day, day + timedelta(days=1),
                                  category="activity", valueQuantity=_qty(int(steps), "{steps}")))
    # Nightly sleep duration and SpO2 while asleep (synthetic when from the generator).
    sl, sp = v.sleep_nightly.c, v.spo2_nightly.c
    nights = await s.execute(
        select(sl.night, sl.bedtime, sl.wake_time, sl.asleep_min, sl.is_synthetic, sp.spo2_mean, sp.t90_pct)
        .select_from(v.sleep_nightly.outerjoin(v.spo2_nightly, (sp.patient_id == sl.patient_id) & (sp.night == sl.night)))
        .where(sl.patient_id == patient_id).order_by(sl.night)
    )
    for night, bed, wake, asleep, synthetic, spo2, t90 in nights:
        key, start, end = night.isoformat(), bed.astimezone(tz), wake.astimezone(tz)
        tags = [TAG, SYNTHETIC_TAG] if synthetic else [TAG]
        device = generator_id if synthetic else wearable_id
        sleep_obs = _obs(twin_id(pid, "sleep", key), pid, device, "93832-4", "Sleep duration", start, end,
                         category="activity", valueQuantity=_qty(round(asleep), "min"))
        sleep_obs["meta"]["tag"] = tags
        resources.append(sleep_obs)
        if spo2 is not None:
            spo2_obs = _obs(twin_id(pid, "spo2-sleep", key), pid, device, "59408-5",
                            "Oxygen saturation during sleep (mean)", start, end, category="vital-signs",
                            valueQuantity=_qty(spo2, "%"),
                            note=[{"text": f"Time below 90 %: {t90} % of sleep"}])
            spo2_obs["meta"]["tag"] = tags
            resources.append(spo2_obs)
    return resources
